name: Generate DocC Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build DocC documentation
        run: |
          mkdir -p docs
          xcodebuild docbuild \
            -scheme TipCalc \
            -derivedDataPath ./DerivedData \
            -destination 'platform=macOS' \
            -skipPackagePluginValidation
          
          doccarchive_path=$(find ./DerivedData -name "*.doccarchive" | head -n 1)

          echo "Found doccarchive at $doccarchive_path"

          xcrun docc process-archive transform-for-static-hosting \
            $doccarchive_path \
            --output-path docs \
            --hosting-base-path tipcalc-docs

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TipCalc-DocC
          path: docs
